server:
  port: 8080

spring:
  application:
    name: whatsapp-chatbot

logging:
  level:
    com.jaruracare.whatsappchatbot: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"